export const FormJob = {
  JobId: "jobId",
  TermType: "termType",
  TermTypeText: "termTypeText",
  Status: "status",
  Title: "title",
  Description: "description",
  SpecialtyId: "specialtyId",
  Scope: "scope",
  LevelFreelancerId: "levelFreelancerId",
  LevelFreelancerIdText: "levelFreelancerIdText",
  BudgetType: "budgetType",
  BudgetTypeText: "budgetTypeText",
  HourlyRateFrom: "hourlyRateFrom",
  HourlyRateTo: "hourlyRateTo",
  CostEstimate: "costEstimate",
  FileAttach: "fileAttach",
  Proposals: "proposals",
  JobSkills: "jobSkills",
  JobSkillsText: "jobSkillsText",
  FileAttaches: "fileAttaches",
  Position: "position",
  CountOfProposal: "countOfProposal",
  CreateDate: "createDate",
  Saved: "saved",
};
export const FormJobSkill = {
  SkillId: "skillId",
  Name: "name",
  Description: "description",
};

export const FormProposal = {
  ProposalId: "proposalId",
  FreelancerId: "freelancerId",
  Status: "status",
  Bid: "bid",
  FeeService: "feeService",
  RealReceive: "realReceive",
  CoverLetter: "coverLetter",
  FileAttaches: "fileAttaches",
};
