export const FormJob = {
  JobId: "jobId",
  TermType: "termType",
  Status: "status",
  Title: "Title",
  Description: "description",
  SpecialtyId: "specialtyId",
  Scope: "scope",
  LevelTalent: "levelTalent",
  BudgetType: "budgetType",
  HourlyRateFrom: "hourlyRateFrom",
  HourlyRateTo: "hourlyRateTo",
  CostEstimate: "costEstimate",
  FileAttach: "fileAttach",
  Proposals: "proposals",
  JobSkills: "jobSkills",
  FileAttaches: "fileAttaches",
};
export const FormJobSkill = {
  SkillId: "skillId",
  Name: "name",
  Description: "description",
};

export const FormProposal = {
  ProposalId: "ProposalId",
  TalentId: "TalentId",
  Bid: "bid",
  FeeService: "feeService",
  RealReceive: "realReceive",
  TargetTime: "targetTime",
  TargetTimeText: "targetTimeText",
  CoverLetter: "coverLetter",
  Description: "description",
  HourlyRate: "hourlyRate",
  ReceiveRate: "receiveRate",
  FrequencyReceive: "frequencyReceive",
  PercentReceivePerTime: "percentReceivePerTime",
  FileAttaches: "fileAttaches",
};
