export const FormClient = {
  ClientId: "clientId",
  Name: "name",
  Email: "email",
  Website: "website",
  SpecialtyId: "specialtyId",
  SpecialtyIdText: "specialtyIdText",
  PeopleInCompany: "peopleInCompany",
  PeopleInCompanyText: "peopleInCompanyText",
  TagLine: "tagLine",
  Description: "description",
  Owner: "owner",
  PhoneNumber: "phoneNumber",
  Address: "address",
  Status: "status",
  StatusText: "statusText",
  ClientType: "clientType",
  ClientTypeText: "clientTypeText",
  Password: "password",
};
