export const FormUser = {
  UserName: "userName",
  Name: "name",
  UserType: "userType",
  UserTypeText: "userTypeText",
  Status: "status",
  StatusText: "statusText",
  EnableLogon: "enableLogon",
  EnableLogonText: "enableLogonText",
  Password: "password",
  FailedLogonCount: "failedLogonCount",
  MustChangePasswordAtNextLogon: "mustChangePasswordAtNextLogon",
  MustChangePasswordAtNextLogonText: "mustChangePasswordAtNextLogonText",
  AccountIsLockedOut: "accountIsLockedOut",
  AccountIsLockedOutText: "accountIsLockedOutText",
  LastTriedOrLogonTime: "lastTriedOrLogonTime",
  LastTriedOrLogonIp: "lastTriedOrLogonIp",
  LastChangePasswordOn: "lastChangePasswordOn",
  ResetPassword: "resetPassword",
};
