export const FormJob = {
  JobId: "jobId",
  ClientId: "clientId",
  TermType: "termType",
  TermTypeText: "termTypeText",
  Status: "status",
  StatusText: "statusText",
  Title: "title",
  Description: "description",
  SpecialtyId: "specialtyId",
  Scope: "scope",
  LevelFreelancerId: "levelFreelancerId",
  LevelFreelancerIdText: "levelFreelancerIdText",
  BudgetType: "budgetType",
  BudgetTypeText: "budgetTypeText",
  HourlyRateFrom: "hourlyRateFrom",
  HourlyRateTo: "hourlyRateTo",
  CostEstimate: "costEstimate",
  FileAttach: "fileAttach",
  Proposals: "proposals",
  JobSkills: "jobSkills",
  JobSkillsText: "jobSkillsText",
  FileAttach: "fileAttach",
  Position: "position",
  CountOfProposal: "countOfProposal",
  CountOfContract: "countOfContract",
  CreateDate: "createDate",
  Saved: "saved",
  Applied: "applied",
};
export const FormJobSkill = {
  SkillId: "skillId",
  Name: "name",
  Description: "description",
};

export const FormProposal = {
  ProposalId: "proposalId",
  FreelancerId: "freelancerId",
  JobId: "jobId",
  Status: "status",
  StatusText: "statusText",
  BidAmount: "bidAmount",
  FeeService: "feeService",
  RealReceive: "realReceive",
  CoverLetter: "coverLetter",
  FileAttach: "fileAttach",
  CreateDate: "createDate",
  JobTitle: "jobTitle",
  StartDate: "startDate",
};
