export const FormContract = {
  ContractId: "contractId",
  JobId: "jobId",
  JobTitle: "jobTitle",
  FreelancerId: "freelancerId",
  RejectDes: "rejectDes",
  Status: "status",
  StatusText: "statusText",
  ContractAmount: "contractAmount",
  FeeService: "feeService",
  RealReceive: "realReceive",
  Remark: "remark",
  StartDate: "startDate",
  EndDate: "endDate",
  ContractResults: "contractResults",
  ProposalId: "proposalId",
  CreateDate: "createDate",
  EndReason: "endReason",
  EndReasonText: "endReasonText",
  EndReasonRemark: "endReasonRemark",
  FileAttach: "fileAttach",
};

export const FormContractResult = {
  ContractId: "contractId",
  ContractResultId: "contractResultId",
  Remark: "remark",
  FileAttach: "fileAttach",
  CreateDate: "createDate",
};
